### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by JimmyLee05** [MixinNetwork/mixin-wallet#7]
<img width="957" alt="截屏2021-08-23 下午1 54 54" src="https://user-images.githubusercontent.com/13815229/130397370-dd98b3a7-1be7-4f82-af33-a5941fcf7d34.png">

**Comment by boyan01** [comment]
It looks like you are not using the master channel?  this project required run with flutter master channel.
```
flutter channel master
```

**Comment by crossle** [comment]
> It looks like you are not using the master channel? this project required run with flutter master channel.
> 
> ```
> flutter channel master
> ```

We should add the env to the readme

**Comment by JimmyLee05** [comment]
Thanks for your help solving this problem
